### ISSUE TITLE
Cygwin fails (deadlock) for -fork=x

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1044]
Currently, we disable (forcibly) within the configure script because it is well know to be broken.

However, I did some work (I will document here), and it was also documented here: #1043 and have actually gotten cygwin to work 'better' with -fork, but it is still busted.  Now with some of the other debugging we have in the logger.c, it is becoming pretty appearent that with our current code, cygwin is failing with some form of race condition / deadlock within the flock() function, interaction between 2 processes.  Possibly we can get this working in some other way (there are other things than flock), or possibly we can escalate this up to the cygwin folks, showing that there IS a problem on their end.

**Comment by magnumripper** [comment]
Sounds like first thing to try is just commenting out all flock() calls and see how well it behaves. I presume O_APPEND on a non-network file system is 100.0% safe under Windows.

**Comment by jfoug** [comment]
That should be VERY easy to check.  AND simple to implement (#ifndef __CYGWIN32__ wrappers)

**Comment by jfoug** [comment]
FU.  worked first time.  You suk!  lol.

**Comment by jfoug** [comment]
I guess the 'non-trivial' may not have been a proper label,

**Comment by magnumripper** [comment]
Ha ha, that was too easy after the brain massage in #1043

**Comment by magnumripper** [comment]
So then it's just a matter of documenting that you've gotta run on a local drive. Everyone will do that anyway but just for good measure.

**Comment by jfoug** [comment]
Agreed, but we would not have gotten there, without the back/forth work trying to explain to each other just wtf was happening.

There are other changes for getting cygwin to fork, but those are trivial, and are already in my testing stuff.

The problem is that cygwin DOES have an flock, so AC finds it.  but (at least the way we are using it), deadlocks.

**Comment by jfoug** [comment]
I am also ONLY running under the cygwin shell. I need to make sure this also works from a windows cmd prompt.  (and also works for cygwin32).  BUT this has not been like this before, that is for sure.

**Comment by magnumripper** [comment]
I bet after a night's sleep one or both of us will come up with an idea regarding those flocks. Maybe we can keep them, with some twist. But as we learnt in #1043 the flock() is not needed at all on a local drive.

**Comment by jfoug** [comment]
my cygwin64 build is absolutely using the -fork, and absolutely working. NOTE, we can not simply turn off FLOCK in AC, or we get an error message listing to NOT use --fork.  We have to build with it, but then make sure we do NOT use it in cygwin.

**Comment by jfoug** [comment]
>  learnt in #1043 the flock() is not needed at all on a local drive.

That is a damn good point. and it actually might speed things up (probably not too much).  I wonder how hard it would be to detect the FS underlying the file itself ?

**Comment by magnumripper** [comment]
Like you said somewhere it's as easy as wrapping them like this (pseudo diff, not sure what macro to use)
```
diff --git a/src/logger.c b/src/logger.c
index 4b96136..02c0f80 100644
--- a/src/logger.c
+++ b/src/logger.c
@@ -108,7 +108,7 @@ static void log_file_flush(struct log_file *f)
        count = f->ptr - f->buffer;
        if (count <= 0) return;
 
-#if OS_FLOCK
+#if OS_FLOCK && !__CYGWIN__
        while (flock(f->fd, LOCK_EX)) {
                if (errno != EINTR)
                        pexit("flock(LOCK_EX)");
```

**Comment by jfoug** [comment]
First, before I go too deep, I need to back out some other changes.  On thing is I commented out some code (needed code), getting to the point where cygwin worked at all.  The call to rec_save in crk_init() is one such thing.  So cygwin working may still be a little premature.

**Comment by jfoug** [comment]
> I bet after a night's sleep one or both of us will come up with an idea 

I will be a night-ranger quiet-riot concert tonite, and the babysitting in morning, so I doubt it will be me that has any thing close to an 'idea', lol.

**Comment by jfoug** [comment]
> -#if OS_FLOCK
+#if OS_FLOCK && !__CYGWIN__

Pretty much exact code I have (but in 2 places)

**Comment by magnumripper** [comment]
You should probably put them in cracker.c too around the LOCK_SH calls

**Comment by magnumripper** [comment]
Oh, and recovery.c too. But if they don't deadlock maybe you can keep them.

**Comment by jfoug** [comment]
I had to comment out rec_save at one time. Now, I have it back in code with no problems.

I really think it is best to comment them all out (for cygwin), until they can show that the code works ALL the time. There certainly could be cases/places where these will fail (even though not failing now). NOTE, there is very little recovery.c testing done in the TS. I am not sure how to auto do that.

**Comment by jfoug** [comment]
```
$ grep flock *.c
cracker.c:      while (flock(pot_fd, LOCK_SH)) {
cracker.c:                      pexit("flock(LOCK_SH)");
cracker.c:      if (flock(pot_fd, LOCK_UN))
cracker.c:              perror("flock(LOCK_UN)");
dmg_fmt_plug.c:                         if (flock(fd, LOCK_EX))
dmg_fmt_plug.c:                                 perror("flock()");
logger.c:       fprintf(stderr, "%s(%u): preparing to call flock(LOCK_EX) %s\n", __FUNCTION__, options.node_min, f->name);
logger.c:       while (flock(f->fd, LOCK_EX)) {
logger.c:                       pexit("flock(LOCK_EX)");
logger.c:       fprintf(stderr, "%s(%u): preparing to call flock(LOCK_UN) on %s\n", __FUNCTION__, options.node_min, f->name);
logger.c:       if (flock(f->fd, LOCK_UN))
logger.c:               pexit("flock(LOCK_UN)");
opencl_dmg_fmt_plug.c:                          if (flock(fd, LOCK_EX))
opencl_dmg_fmt_plug.c:                                  perror("flock()");
recovery.c:     if (flock(rec_fd, lockmode)) {
recovery.c:                     pexit("flock(%d)", lockmode);
recovery.c:     if (flock(rec_fd, LOCK_UN))
recovery.c:             perror("flock(LOCK_UN)");
```

**Comment by jfoug** [comment]
Note, I will probalby have to test a much longer run, to make sure things like recovery, and cracker (pot reload), works with no problems, once I add the ```  && !__CYGWIN__ ``` wrapper to the FLOCK code.

**Comment by jfoug** [comment]
I did get a deadlock in cygwin build, but that was before I commented out the flocks in cracker/recovery.  I am re-running the TS now, after changing those.

**Comment by jfoug** [comment]
a285f44 is many changes. NOTE, I still want to test this some more (and do not have time for a while), before calling this good.  I need to test more on cygwin64, and have not tested at all on cygwin32.

Also needing tested is running this outside of a cygwin bash shell.

**Comment by magnumripper** [comment]
Good Stuff. I saw you added a debug print right before trying to lock, that was one thing I was going to suggest. Another thing one could try is something like this:

Current code
```C
        while (flock(f->fd, LOCK_EX)) {
                if (errno != EINTR)
                        pexit("flock(LOCK_EX)");
        }
```

Debug code
```C
        while (flock(f->fd, LOCK_EX | LOCK_NB)) {
                if (errno != EINTR && errno != EWOULDBLOCK)
                        pexit("flock(LOCK_EX)");
                fprintf(stderr, "%s(%u) retrying lock\n", __FUNCTION__, options.node_min);
                sleep(1);
        }
```
Well, something like this. This will be awfully slow, always waits a full second, but you will see whether this one too deadlocks, or if it's just blocking lock calls that do.

**Comment by magnumripper** [comment]
Note also that we need to answer this question: Are we really sure Windows has an *atomic* O_APPEND? Some googling indicates it does not. Cygwin may emulate it with just a non-atomic seek-to-end before write, but that will lead to guaranteed file corruption unless we can find out how to lock files properly.

For locking, we could try fcntl() instead. Or perhaps lockf()? Or even some Windows-specific code - maybe that is the safest bet and we'll have it -D__CYGWIN__ anyway.

**Comment by magnumripper** [comment]
http://www.perlmonks.org/?node_id=486488
*Note that Win32 doesn't do the seek-then-write atomicly, so you should lock if your code might be/is run on Win32. Also note that if you didn't use binmode (which is likely true and usually for good reason), then the order of things is seek, then newline conversion, then write, which makes the race even racier.*

**Comment by magnumripper** [comment]
Better news: https://cygwin.com/cygwin-ug-net/ov-new1.7.html

*What's new and what changed in Cygwin
...
What's new and what changed from 1.5 to 1.7
...
Implement atomic O_APPEND mode.*

**Comment by magnumripper** [comment]
Also some info on what is "supposed" from POSIX: http://stackoverflow.com/questions/1154446/is-file-append-atomic-in-unix

**Comment by magnumripper** [comment]
Oh, and here's a test script!
http://www.notthewizard.com/2014/06/17/are-files-appends-really-atomic/

**Comment by magnumripper** [comment]
OSX only seem to have a 256 byte max without locking
```
$ ./atomic.sh 256
Launching 20 worker processes
Each line will be 256 characters long
Waiting for processes to exit
Testing output file
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
All's good! The output file had no corrupted lines. 

$ ./atomic.sh 257
Launching 20 worker processes
Each line will be 257 characters long
Waiting for processes to exit
Testing output file
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Found 1000 instances of corrupted lines
```

**Comment by jfoug** [comment]
I've been warning folks that this type fork code is VERY tricky. That some OS's babysit u does not mean it's great code for general purpose. It is good we have been digging in to learn the good and the ugly.  Btw, Quiet Riot just got done. Waiting for Night Ranger.

**Comment by jfoug** [comment]
I will work with that test script later

**Comment by jfoug** [comment]
Here is a run under cygwin64 (updated pretty recently, last Dec I think).  NOTE, this only allows for testing under cygwin bash terminal.  It does not allow testing a native cygwin 'program' that is run under Win32 (64) cmd shell.  While they are similar, there are some differences which I am not fully aware of. It could be for this case that there is no difference at all. A HUGE amount of differences are due to nuances in the shells.

One note to cygwin, I am not 100% sure that processes launched with the & in a loop like that, are not all completed fast enough, so that there is no overlapped running of processes. Well, now I am more sure cygwin 'IS' working properly, since adding 1 byte to length in cygwin32 did show the problem perfectly.

```
CYGWIN-64
$ ./tst-appends.sh
Buffer length not specified, defaulting to 4096
Launching 20 worker processes
Each line will be 4096 characters long
Waiting for processes to exit
Testing output file
All's good! The output file had no corrupted lines.

Launching 20 worker processes
Each line will be 8192 characters long
Waiting for processes to exit
Testing output file
All's good! The output file had no corrupted lines.

I am not going over 8192 chars, until the compare is changed. Just takes too long.
```

```
CYGWIN-32
$ ./tst-appends.sh 1024
Launching 20 worker processes
Each line will be 1024 characters long
Waiting for processes to exit
Testing output file
All's good! The output file had no corrupted lines.

$ ./tst-appends.sh 1025
Launching 20 worker processes
Each line will be 1025 characters long
Waiting for processes to exit
Testing output file
Found 50 instances of corrupted lines

```
Ubuntu64 14.4_LTS on virtualbox (ext4fs /tmp/) 

NOTE, I am getting exact same results on the vboxfs file system???  But I bet the shell is locking with flock() on the >>

$ ./tst-appends.sh 1008
Launching 20 worker processes
Each line will be 1008 characters long
Waiting for processes to exit
Testing output file
All's good! The output file had no corrupted lines. 

$ ./tst-appends.sh 1009
Launching 20 worker processes
Each line will be 1009 characters long
Waiting for processes to exit
Testing output file
Found 66 instances of corrupted lines
```


This is a modified script so that the test will be done on vboxsf drive and re-run

**Comment by jfoug** [comment]
> For locking, we could try fcntl() instead. Or perhaps lockf()? Or even some Windows-specific code - maybe that is the safest bet and we'll have it -D__CYGWIN__ anyway.

I think that is very good idea.  During a TS run, I actually locked up the machine, It was still working, but even the mouse would only move a few dozen pixels ever 20-30s or so.   Something had enough threads hard locked and busy, and was not even giving it up to the OS. So it 'almost' works, without any locking, but really not good enough.   I really think fcntl() may be the way to do (but it could be the lockf()  )   The cygwin page you found DID list that each of these API implementations WAS independent of the others.

**Comment by jfoug** [comment]
I am doing fcntl() for cywin in logger.c to see how things go.  But from this page:

http://www.informit.com/articles/article.aspx?p=23618&seqNum=4

```
Linux provides another implementation of file locking with the flock call. The fcntl version has a major advantage: It works with files on NFS3 file systems (as long as the NFS server is reasonably recent and correctly configured). So, if you have access to two machines that both mount the same file system via NFS, you can repeat the previous example using two different machines. Run lock-file on one machine, specifying a file on an NFS file system, and then run it again on another machine, specifying the same file. NFS wakes up the second program when the lock is released by the first program.
```

So we may really want to look at this, along with ask Solar on to why his choice for that BSD flock() interface??  It may be that it is available on my platforms.  BUT as per that statment, it sounds like this 'may' be a much better way to go, even handling NFS (possibly).

**Comment by jfoug** [comment]
Ok, I implemented a 'simple' fcntl.   simply following exact same instructions as on 

http://www.informit.com/articles/article.aspx?p=23618&seqNum=4

Cygwin runs, but dead locks.  I will rebuild with LOCK_DEBUG and see if there is anything that stands out.  NOTE, with no locking, cygwin runs, but like i said, at some point, it did totally bone my system, to the point that the OS, was starved (hal layer I 'think' was still working).

**Comment by magnumripper** [comment]
> The fcntl version has a major advantage: It works with files on NFS3 file systems (as long as the NFS server is reasonably recent and correctly configured).

This is very outdated information (2001!). I know flock() works fine in Linux w/ NFS and has done so for six years or more.

**Comment by magnumripper** [comment]
I presume Solar picked flock() for a good reason, since fcntl() is more portable if I got things right. We should simply ask him.

**Comment by magnumripper** [comment]
> NOTE, I am getting exact same results on the vboxfs file system???  But I bet the shell is locking with flock() on the >>

I doubt that. If it does, you would get zero failures regardless of size - you should be able to run it with 65536 and it would still not fail.

**Comment by magnumripper** [comment]
I'm writing to john-dev right now, asking Solar.

**Comment by magnumripper** [comment]
05b51935 wraps up Jim's initial work and make fcntl() the default locking scheme. After testing, we can hopefully close this.
