### ISSUE TITLE
Revise SSEi_FLAT_IN for simpler code and/or performance

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1220]
Food for thoughts, @jfoug 

I think we have far too few formats that use "flat buffers" for the MD4/5 and SHA1/2 intrinsics functions. Reason is obviously we did not support it until last year or so.

Random ideas:
* We should also add SSEi_FLAT_OUT, and strive to really optimize that code too.
* Most formats (definitely all slow ones) should be converted to use both FLAT_IN and FLAT_OUT. This would take away almost all x86-SSE/AVX-specific code and #ifdefs from the formats (as currently is the case with eg. sapH format). It would make future optimizations appear in one central place. And it would make future support for non-x86 intrinsics support simpler.
* Actually it **may** be that SSEi_FLAT_IN would make even raw formats faster (not FLAT_OUT though). We should try it. My awfully looking but awfully effective "32-bit set_key" functions may be hard to beat but OTOH they work on one key at a time. SSEi_FLAT_IN may do it with vector intrinsics. Even if it ends up about the same speed, it would be worth it just for dropping special code from the formats.

**Comment by magnumripper** [comment]
BTW the NT2 format is probably not a candidate for flat input - it takes codepage/UTF-8 input and places UTF-16LE right into the interleaved SIMD buffer. Somehow it's even faster than raw-md4. Adding a flat buffer inbetween can only make it slower I guess.

But I will try it out with raw-md5 and see what speed I can cram out if it.

**Comment by magnumripper** [comment]
> I will try it out with raw-md5 and see what speed I can cram out if it.

LOL, it's 20% slower - I guess it's really hard to beat the 32-bit interleaved set_key().

**Comment by magnumripper** [comment]
Just maybe we want a SSEi_CLEAN flag too, to be used with SSEi_FLAT_IN. That would be for feeding a flat buffer that ends with a NULL and may not be cleansed after the NULL - just like any char array we would pass to OpenSSL.

If we can handle that really fast on SIMD side of it, we're good. I can actually (just barely) beat original speed if I nick Tavis' set_key() from raw-sha1-ng, but max length is only 15 (unless we have >= AVX2). I will continue digging into this.

**Comment by magnumripper** [comment]
I added these (just to the enum so far ;-)
```C
/*
 * SSEi_CSTRING_IN
 * Input will be just as for OpenSSL: A normal char[COEF][64] array where
 * each string ends in NULL, with no 0x80 or length prepared. The intrinsics
 * function needs to take care of that as well as cleaning (after NULL),
 * shuffling and possibly do endian swapping if applicable.
 *
 * SSEi_FLAT_OUT
 * Output will be just as from OpenSSL. Swapped if applicable, not interleaved.
 * This should only be used for "final" crypt (and only for slow formats).
 *
 */
```

**Comment by magnumripper** [comment]
I had a look at SSEi_FLAT_OUT. Even AVX2 lacks scatter ops so only slow formats like PBKDF2 would be applicable (and only for the sake of simplifying format code). Perhaps it's not worth bothering with it at all, at least until there are fast scatter functions available.

**Comment by jfoug** [comment]
there are a couple things good about the flat formats.  Usually they are NOT faster.  They 'can' be close, but a huge improvement in speed is proper buffer manipulations. We have proper buffer handling in the interleaved code.  It may be possible to re-work buffer manipulations for flat buffers to improve speed a great deal.  

The good improvements are, 

1. much easier handling of multiple buffer length hashes.  It is still best to group the SIMD buffer group to all have the same length (i.e. number of buffers), but it is technically not a requirement, and within dynamic, I believe that it work even if only some do multiple buffers, by harvesting off the results as they are done, but continuing forward as long as any buffers are not complete.

2. a little easier to go between C buffers and SIMD buffers.

But as you are finding out, there really is still a need for the ugly interleaved code, IF you expect faster performance.   I have given a lot of thought to dropping ALL interleaved code in dynamic, and simply using flat.   Dynamic would be considerably more trivial code if all code used flat code.  BUT the performance on numerous formats would degrade, along with there are other users out there with their own dyna scripts that would fail to run if all the legacy code went away.

**Comment by magnumripper** [comment]
I have a vague idea about SSEi_CSTRING_IN implementation. Very vague :laughing: 

Basically it's similar to Tavis' set_key() in raw-sha1-ng or mgetl() in wordlist.c except they are for a single key and we'll do it with a vector. Something like this:
- We do a vectorized search for the end-of-string NULL at the same time as we gather the flat data into the vector buffer.
- When a NULL is found, we set (or clear) a mask accordingly, so the rest of the copy will only result in zeros for that index.

I'm pretty sure this can be done but it's not trivial.

**Comment by magnumripper** [comment]
I implemented SSEi_FLAT_OUT in b6c004964 (and deprecated SSEi_SWAP_FINAL which wasn't used anywhere).

8ebb42dde changed a bunch of formats (that previously did marshalling & endian swap on their own) to use the new feature.

No speed gain (nor loss), but simpler host code. And we may add actual scatter instructions for SHA512 and MIC - @zzlei do you wanna give that a try?

**Comment by jfoug** [comment]
NOTE, this change required a ```make clean```  or I had failures all over the place.  We must  not have enough dependencies on sse-intrinsics.h or something.

**Comment by magnumripper** [comment]
The format files does not depend on sse-intrinsics-load-flags.h because the dependecy generator does not recurse.

**Comment by jfoug** [comment]
I understand that, but it is still a problem.  Any change like you made, (where you changed existing numbers), caused a requirement of the formats to be built.  It is not that huge of an issue.  The dependency generator has been a great improvment over always having to make -s clean && make -sj8   However, there still can be times clean is needed (like this one).

**Comment by magnumripper** [comment]
I'm thinking we could add a single level of recursion to it. That should catch almost 100% good and hopefully no bad.

**Comment by jfoug** [comment]
The only 'bad' I can think of is recursive includes.  But if you limit to 1 level, that is not an issue.

**Comment by zzlei** [comment]
> And we may add actual scatter instructions for SHA512 and MIC

I wasn't catching up with this thread. Where should I start?

**Comment by magnumripper** [comment]
Each hash function in sse-intrinsics.c now has this output alternative:
```
	if (SSEi_flags & SSEi_FLAT_OUT) {
		SHA256_PARA_DO(i)
		{
			uint32_t *o = (uint32_t*)&out[i*8*VS32];
			uint32_t j, k;
			vtype tmp[8];

			vstore(&tmp[0], vswap32(a[i]));
			vstore(&tmp[1], vswap32(b[i]));
			vstore(&tmp[2], vswap32(c[i]));
			vstore(&tmp[3], vswap32(d[i]));
			vstore(&tmp[4], vswap32(e[i]));
			vstore(&tmp[5], vswap32(f[i]));
			vstore(&tmp[6], vswap32(g[i]));
			vstore(&tmp[7], vswap32(h[i]));

			for (j = 0; j < VS32; j++)
				for (k = 0; k < 8; k++)
					o[j*8+k] = ((uint32_t*)tmp)[k*VS32+j];
		}
	}
```
From AVX512, there are scatter functions that may be used to do this more efficiently. I'm not 100% sure they are applicable though.

**Comment by zzlei** [comment]
Something like this should do the trick:
```c
vtype idxs = vset_epi32(15<<2,14<<2,13<<2,12<<2,
                        11<<2,10<<2, 9<<2, 8<<2,
                         7<<2, 6<<2, 5<<2, 4<<2,
                         3<<2, 2<<2, 1<<2, 0<<2);

vscatter_epi32(o + 0, idxs, vswap32(a[i]), 8);
vscatter_epi32(o + 1, idxs, vswap32(b[i]), 8);
vscatter_epi32(o + 2, idxs, vswap32(c[i]), 8);
vscatter_epi32(o + 3, idxs, vswap32(d[i]), 8);
vscatter_epi32(o + 4, idxs, vswap32(e[i]), 8);
vscatter_epi32(o + 5, idxs, vswap32(f[i]), 8);
vscatter_epi32(o + 6, idxs, vswap32(g[i]), 8);
vscatter_epi32(o + 7, idxs, vswap32(h[i]), 8);
```

I'll test it.

**Comment by magnumripper** [comment]
You can benchmark it using the SybaseASE format, I think it's fast enough to show a difference.

**Comment by zzlei** [comment]
I applied this change to all SHA1, SHA256 & SHA512, and picked a few formats for benchmarking (on MIC).

**office** (SHA1 ?)
[before]
Raw:    13241 c/s real, 55.1 c/s virtual
[after]
Raw:    13241 c/s real, 55.3 c/s virtual

**sybasease** (SHA256)
[before]
Many salts:     1459K c/s real, 7194 c/s virtual
Only one salt:  1974K c/s real, 8287 c/s virtual
[after]
Many salts:     1457K c/s real, 7009 c/s virtual
Only one salt:  2029K c/s real, 9131 c/s virtual

**blackberry-es10** (SHA512)
[before]
Raw:    327680 c/s real, 1366 c/s virtual
[after]
Raw:    329879 c/s real, 1371 c/s virtual


I think the corresponding code path is taken too infrequently to effectively affect the overall performance.

**Comment by magnumripper** [comment]
Only SybaseASE w/ single salt is fast enough to affect performance. And it's indeed a little faster.

**Comment by magnumripper** [comment]
BTW something seems to be wrong with SybaseASE , the "many salts" figure is slower than "one salt". This seems to be MIC specific. Here's my laptop
```
$ ../run/john -test -form:sybasease 
Will run 8 OpenMP threads
Benchmarking: SybaseASE, Sybase ASE [SHA256 128/128 AVX 4x]... (8xOMP) DONE
Many salts:	3833K c/s real, 518789 c/s virtual
Only one salt:	3620K c/s real, 518748 c/s virtual
```

**Comment by magnumripper** [comment]
Lei committed a1894a8d for SHA1/256/512 and I added 98e5fe73 for MD4/5

**Comment by magnumripper** [comment]
For the record I revised SSEi_SKIP_ADD (which was unused). I renamed it to SSEi_REVERSE_STEPS and it's now documented as "at least skipping the adds". For MD4 it now reverses just as much as Alain's NT format, and this is now used in our NT2 (now labeled NT) code. 10% boost!

To my disappointment, we didn't quite break the 100M wall per core on well:
```
Benchmarking: NT [MD4 256/256 AVX2 8x3]... DONE
Raw:	99553K c/s real, 99553K c/s virtual
```

But due to AVX2 support we're a good deal faster than Alain's assembler format:
```
Benchmarking: NT-old [MD4 128/128 X2 SSE2-16]... DONE
Raw:	60151K c/s real, 60758K c/s virtual
```

The process is rather simple, I'll do it for more raw formats soon.
