### ISSUE TITLE
zip2john can't handle "big" zip files

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2352]
See https://github.com/magnumripper/JohnTheRipper/issues/2219#issuecomment-264264126

I created the simple test case seen below (on well). 

```
$ ls -lh 0.txt
-rw-r--r--. 1 claudio claudio 1.7K Dec  3 03:25 0.txt

$ ls -lh f0.txt
-rw-r--r--. 1 claudio claudio 7.8G Dec  3 03:54 f0.txt
```
```
zip zero 0.txt -e
zip fzero f0.txt -e
```

```
$ unzip -l fzero #Ok
$ unzip -t fzero
[...]
No errors detected in compressed data of fzero.zip
```

zip2john handles zero.zip but can't handle fzero.zip. 
- I saw it exits without a reasonable message or a hash;
- I saw fread errors.

**Comment by claudioandre** [comment]
BTW: i tried JtR with a zip containing 111210 files. No problems at all.

```
$ ls -lh todos.zip 
-rw-r--r--. 1 claudio claudio 366M Dec  3 05:05 todos.zip
[...]

$ ../run/john  ~/hash
Using default input encoding: UTF-8
Loaded 1 password hash (PKZIP [32/64])
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
john             (todos.zip)
1g 0:00:00:00 DONE 2/3 (2016-12-03 05:08) 4.761g/s 212904p/s 212904c/s 212904C/s 123456..skyline!
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

**Comment by magnumripper** [comment]
#2219 was a memory leak per-file, fixed now. I guess this issue is more about trying to keep all of a huge file in memory. So a system with enough memory of swap will handle it fine. The solution would be to memory map the file instead of alloc+fread. And perhaps some adjusting of the toHex() function so it doesn't try to allocate an output string of another twice the data size (not sure it does but I can imagine it does).

**Comment by magnumripper** [comment]
Oh, we also probably have 32-bit limitations. So even a system with 128 GB memory would not handle this file.

**Comment by jfoug** [comment]
I am almost 100% sure we can get zip2john to work for any .zip file. It was poorly written, with lots of memory consumption that should not be done that way.

However, we will have 32 bit type issues for pkzip format.  We may be able to work around those issues, by only pulling into memory file data blobs that are of a certain size, and if the blob is over that, we simply keep an open file handle, the offset, and size, and when we have to compute the crc32, we read from disk each time.   That will allow john to 'work' for any .zip file, but on the really  (REALLY) big ones (say 250gb), it will slow down quite a bit, since every checksum hit will have to read that entire blob from disk. BUT at least it would allow john to work.   If someone is trying to crack something that large, then they are willing to wait the time needed (I would assume).  Trying to crack something like that would usually be a something like a disk partition backed up, where they 'sort' of know the password, but trial by hand is not working, so they are using mangling rules.  But allowing john to actually work, even if it is reading the disk a bunch is better than simply coring or not loading the data at all.

**Comment by jfoug** [comment]
I think this also brings up going back to a mode where we do not store the blob in the input hash (as hex).  This sorts of rolls back the large hash handling mode, but possibly in extreme situations, we really should roll that behavior back.  @magnumripper can you comment on this thought process please.

**Comment by magnumripper** [comment]
I think we should just change all code to using 64-bit fseek/ftell and size_t/off_t for any sizes. That should mean we can handle any size as long as we're a 64-bit build. A 32-bit build will have 32-bit limitations and frankly I couldn't care less! I hear the hashcat team already discussing dropping support for 32-bit! I definitely think we should keep supporting 32-bit, but there's no point jumping through hoops for edge cases.

Second, we should change the toHex() function to output it's data to a stream (ie. stdout) instead of allocating and returning a buffer twice the size of input data. No alloc needed at all.

Finally, for extreme cases we could simply use a memory map of the input file instead of allocating/freeing any buffer at all. That's much simpler to code, and ends up working optimally for systems with very very much **or** very very little memory - the virtual memory handler takes care of everything. Having said that, I doubt it's needed. I haven't ever seen a zip file that large. Most huge archives seem to be RAR.

I see no need for reverting to non-blob. Why would we do that? Yes, a 4 GB file may end up an 8 GB input file. We could do a little better using Base-64 but it will still be 5.3 GB. But that will be very rare (eg. the smallest file in an archive is that big) and it will work just fine on a 64-bit build.

**Comment by magnumripper** [comment]
> I see no need for reverting to non-blob.

What I **can** see coming, sooner or later, is some alternate, binary, input format. Or btw even better, DROP the need for zip2john (et al) and let you do things like `./john archive.zip`. To support that we'd need to add something(s) to the format interface.

**Comment by ddreggors** [comment]
I think this issue may still exist in 1.8.0-jumbo-1.

When I run zip2john all works as expected and a 4G hash file is created:
`$ ./zip2john encrypted.zip > encrypted.hash
ver 2.0 Movie.zip->017 HD-TS x264-CPG.mkv PKZIP Encr: cmplen=2142276603, decmplen=2143196027, crc=513DE5A7
$ ls -l ~/Downloads/Movie.hash 
-rw-rw-r--. 1 ddreggors ddreggors 4284553336 May 12 13:48 encrypted.hash`

However running john against this file cause a core dump with invalid pointer:
`$ ./john --show ~/Downloads/Movie.hash
*** Error in `./john': munmap_chunk(): invalid pointer: 0x00007fef6c0e6010 ***
`

**Comment by ddreggors** [comment]
Folowing up to that last comment I would like to add that Fedora has john (not jumbo) in yum repos. Installing it and using john against the previous hash file yields this:

```
$ john --show ./encrypted.hash
ecd67fb84e4f2c754613624bcf25b7011f97fbaba650272d26c54e321539701c20e1ad3f9f1adecd82e9d3d40e84e846604688ea9dd3aa8d77bff79e3cb5fe452b094*$/pkzip2$:NO PASSWORD::::encrypted.zip
```

Since this zip is encrypted and has a password, zip2john from jumbo seems to have failed

**Comment by magnumripper** [comment]
> I think this issue may still exist in 1.8.0-jumbo-1.

Jumbo-1 is like three years old and we are literally several **thousands** of commits past it. Did you mean bleeding Jumbo (as in latest Github version)?

**Comment by magnumripper** [comment]
This issue should be fixed since last week or so. Needs testing.

**Comment by ddreggors** [comment]
I am sorry yes... the bleeding was the one I meant.

```
$ ./john --list=build-info |head -n 1
Version: 1.8.0.9-jumbo-1-bleeding
```

This (1.8.0.9-jumbo-1) is what I was using in the above not 1.8.0-jumbo-1.

**Comment by ddreggors** [comment]
> This issue should be fixed since last week or so. Needs testing.

It was not as of two days ago, that is when I downloaded the version I was using to show these errors.

**Comment by ddreggors** [comment]
Confirmed

```
$ ./john --show ../../encrypted.hash
0 password hashes cracked, 1 left

```

Still does not crack password but at least it did not core dump and it actually says 0 cracked, 1 left :+1:

**Comment by tarkin2020** [comment]
I'm not sure but I think this problem still persits. I used latest jumbo bleeding release and the zip2john is just producing a several gigabytes large hash file. 
is there anything I need to change on code or my machine?
the zip file is 8gb large and is containing one file with 15gb.

**Comment by magnumripper** [comment]
Unfortunately an 8 GB file will produce 16 GB worth of hex output and you will need a lot of memory (and preferably a lot of swap as well) to load it. Also, even if you have 64 GB of memory that 'hash' will be slow as hell to attack since we'll need to calculate a CRC on 8 GB of data for each candidate tried (unless we can early reject some of them).

**Comment by martinlang83** [comment]
does not sound good. so probably there is no possibility to calculate this
password?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Mo., 2. März 2020 um 10:30 Uhr schrieb magnum <notifications@github.com>:

**Comment by magnumripper** [comment]
Well if you do have a lot of memory and the password isn't too strong, it should be possible for sure. In my opinion, a modern computer shouldn't have less than 32 GB of memory.

**Comment by martinlang83** [comment]
well it is for a big customer and i think he would also pay for a large
machine from aws maybe. so memory should not be a problem.

funny wise. I tried again zip2john with -o and -c option and it gave me a
small enc hash:

MailBackup.zip/MailBackup.pst:$pkzip2$1*1*1*0*8*24*ec11*560c*1b4216d48b6433ae4de35274b9e2d7c6d29ef7ab2b741583e91aec0be27b920a2df8339f*$/pkzip2$:MailBackup.pst:MailBackup.zip::c:\Users\m.lang\Downloads\MailBackup.zip

and john outputs:
john --show enc.hash
0 password hashes cracked, 1 left

that doesnt look to bad or do I misunderstand this?!



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Mo., 2. März 2020 um 10:36 Uhr schrieb magnum <notifications@github.com>:

**Comment by magnumripper** [comment]
I was just going to suggest you running `zipinfo` on the archive. This looks pretty good, I think. The fact zip2john picked a larger file instead is kind of a bug.

**Comment by magnumripper** [comment]
Oh btw you willl crack it *immediately* using single mode 😄

**Comment by martinlang83** [comment]
thanks, but I think it has not worked. i john on the hash and he found the
"password" but when I try to extract it zip claims the password is wrong :-(

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Mo., 2. März 2020 um 10:42 Uhr schrieb magnum <notifications@github.com>:

**Comment by magnumripper** [comment]
So a false positive, too bad. Perhaps you used the `-c` option in some invalid way. What's the output of `zipinfo Mailbackup.zip`?

**Comment by martinlang83** [comment]
zipinfo tells:

Archive:  MailBackup.zip
Zip file size: 9397790087 bytes, number of entries: 1
-rw-a--     6.3 fat 18250023936 Bx defN 19-May-22 10:48 MailBackup.pst
1 file, 18250023936 bytes uncompressed, 9397789797 bytes compressed:  48.5%


Am Mo., 2. März 2020 um 10:46 Uhr schrieb magnum <notifications@github.com>:

**Comment by martinlang83** [comment]
also the unzip looks wired with the "wong" password:

unzip MailBackup.zip
Archive:  MailBackup.zip
[MailBackup.zip] MailBackup.pst password:
 inflating: MailBackup.pst           bad CRC 04591a32  (should be ec114727)
   (may instead be incorrect password)




Am Mo., 2. März 2020 um 10:56 Uhr schrieb Martin Lang <
mart.lang.in@gmail.com>:

**Comment by magnumripper** [comment]
OK, then I believe you'll simply need a lot of memory. However, if you can confirm the cracking speed ends up to be very poor (compared to a benchmark of pkzip format), we could probably mitigate that by implementing file magic support for `.pst` files.

https://www.file-recovery.com/pst-signature-format.htm

**Comment by tarkin2020** [comment]
thanks a lot for your support.
I will try than with a propper machine. what would you suggest as hardware
parameters?

**Comment by solardiz** [comment]
@magnumripper Besides or instead of support for specific file types, we could detect low entropy or long sequences of 0's (or any same byte values, for that matter) for any large files (where CRC calculation would be expected to be slower). The problem is in what we do when we do not see low entropy (like we won't most of the time, because the tested password will be wrong) - do we calculate CRC anyway? If so, there won't be any speedup. Perhaps we need an option (exposed to the user) that would disable CRC checks and replace them with entropy check of first N bytes (parameter to that option). This could even be a `zip2john` option (rather than a `john` one, even though it primarily affects `john`), so that we won't have to have a format-specific option in `john` and we'd also avoid the "non-hash" file size and RAM requirement issue.

@martinlang83 You could also consider known-plaintext attack if you need the decrypted data rather than the password:

https://www.openwall.com/lists/john-users/2019/05/20/3

**Comment by tarkin2020** [comment]
thank you @magnumripper  helped me to use it propper. I now have a 8GB hash file. I run john against this hash file. it is quite slow more or less 60000p/s.

@solardiz thanks a lot but I dont quite understand the plaintext attack thing. I know that in my zip there is one large PST file (MS Outlook). so i dont think pst is a plain text format?!

**Comment by solardiz** [comment]
@martinlang83 We're already abusing this GitHub issue too much instead of discussing the JtR aspects on john-users, and the known-plaintext attack is nearly off-topic for both, but you can read about such attacks in general here:

https://en.wikipedia.org/wiki/Known-plaintext_attack

For pkzip encryption in particular, attack is possible when you know (or guess) at least first 11 bytes of plaintext - and plaintext does not mean plain text, it means original unencrypted data. For many file formats, first 11+ bytes are part of the file format specific header and are not specific to the file's contents, so can be taken from another file of the same format.

**Comment by magnumripper** [comment]
> I now have a 8GB hash file. I run john against this hash file. it is quite slow more or less 60000p/s.

I just now committed file magic support for zip2john (use it by simply adding `-m` to your zip2john command line), but in my tests with a several GB file, it made almost no difference - I got over 38Mp/s even without it (due to our excellent early rejection of invalid Huffman data). My guess is the 60Kp/s you were seeing will soon increase with several orders of magnitude (there's a long start-up time that skews the initial statistics)

**Comment by tarkin2020** [comment]
Very Cool. thanks a lot! Do you use any special commands? I'm not getting
this high performance. I get 36Mps on a 16core machine. so each core about
2MP/s.

this seems still very slow :-(


Am Mo., 2. März 2020 um 23:00 Uhr schrieb magnum <notifications@github.com>:

**Comment by solardiz** [comment]
> I get 36Mps on a 16core machine. so each core about 2MP/s.

Is this with `--fork=16`? Our PKZIP format isn't OpenMP-capable, and needs fork.

**Comment by tarkin2020** [comment]
Yes with fork 16

Solar Designer <notifications@github.com> schrieb am Di. 3. März 2020 um
20:30:

**Comment by magnumripper** [comment]
> Our PKZIP format isn't OpenMP-capable, and needs fork.

Yes the PKZIP format is OpenMP-capable. It scales fair enough, but fork may be faster. The speed I reported was using 16 threads (8 real cores) IIRC.
