### ISSUE TITLE
Windows build no opencl devices

### ISSUE THREAD

**Issue by kevtheskin** [magnumripper/JohnTheRipper#3647]
Hello there,
Can someone help me get John working on my Win10 pro please This is the build 
Version: 1.8.0.13-jumbo-1-bleeding-1f1a862 2019-01-31 23:28:54 +0100
Build: cygwin 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
CPU fallback binary: john-xop
OMP fallback binary: john-avx2-non-omp
$JOHN is
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 6.4.0
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01000210f      (loaded: 0100020ef)
OpenSSL 1.0.2p  14 Aug 2018     (loaded: OpenSSL 1.0.2n  7 Dec 2017)
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
Section [opencl-device] not found.
help[:WHAT], subformats, inc-modes, rules, externals, ext-modes, ext-hybrids,
ext-filters, ext-filters-only, build-info, hidden-options, encodings,
formats, format-details, format-all-details, format-methods[:WHICH],
format-tests, sections, parameters:SECTION, list-data:SECTION,
opencl-devices, <conf section name>
Does not see my Gpu
I am running a Nvidia 1080 card which works fine with hashcat. Anyhelp would be much appreciated thanks. Kev

**Comment by claudioandre-br** [comment]
Well, here is not a support forum. But, since you are using (what I call) the Windows package, I have to try to ask for more information.
* the message `Section [opencl-device] not found` seen above suggests a typo. It should be (note the S):

```
john --list=opencl-devices
``` 

Please, try that. If things are **not** Ok, I will open a new issue to handle it.

Thanks
****
PS: do you have a file named  ```nvopencl.dll``` in your installed in your computer?

**Comment by kevtheskin** [comment]
Hi there sorry for asking this question. I know its not a forum as such but where else can us noobies get help.
Any here is the result to your string
C:\Users\Kevo\Desktop\win_x64\run>john --list=opencl-devices
Error: No OpenCL-capable platforms were detected by the installed OpenCL driver.
Error: No OpenCL-capable devices were detected by the installed OpenCL driver
Hashcat works ok with Gpu
Cheers Kev

**Comment by claudioandre-br** [comment]
> but where else can us noobies get help?

- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (make sure you set a descriptive message Subject when you post).

Please, try to see what `*opencl*.dll` files you have installed on your system (use the Windows find files).
****

But it is Interesting. Why people are not aware of the list? Solar?

**Comment by kevtheskin** [comment]
opencl.dll v2.21.0 9 in total 32/64

Kev

**Comment by kevtheskin** [comment]
3x nvopencl32.dll and 3x nvopencl64.dll all located in the FileRepository

Cheers Kev

**Comment by claudioandre-br** [comment]
Fixed upstream https://github.com/claudioandre-br/packages/commit/dd1c6a3639b47711767bbf783b9c7add903ca265

**Comment by kevtheskin** [comment]
> 
> 
> Fixed upstream [claudioandre-br/packages@dd1c6a3](https://github.com/claudioandre-br/packages/commit/dd1c6a3639b47711767bbf783b9c7add903ca265)

Hello Claudio thanks for your time. Is this the fix for not seeing my Gpu if so how do I use it. Cheers Kev

**Comment by claudioandre-br** [comment]
* Edit the file `C:\Users\Kevo\Desktop\win_x64\etc\OpenCL\vendors\nvidia.icd `
* Change `nvopencl.dll` to `nvopencl64.dll`

**Comment by magnumripper** [comment]
> But it is Interesting. Why people are not aware of the list? Solar?

Because mailing lists are "so 1990", and many of these users weren't even born back then.

**Comment by kevtheskin** [comment]
> 
> 
>     * Edit the file `C:\Users\Kevo\Desktop\win_x64\etc\OpenCL\vendors\nvidia.icd `
> 
>     * Change `nvopencl.dll` to `nvopencl64.dll`

Hello Claudio thanks for this but still the same error 
C:\Users\Kevo\Desktop\win_x64\run>john.exe --list=opencl-devices
Error: No OpenCL-capable platforms were detected by the installed OpenCL driver.
Error: No OpenCL-capable devices were detected by the installed OpenCL driver

**Comment by claudioandre-br** [comment]
I have to try to reproduce your environment. 
* Meanwhile, you should check if the location of the library is correct, try to use `nvopencl32.dll`, etc.

**Comment by kevtheskin** [comment]
> 
> 
> I have to try to reproduce your environment.
> 
>     * Meanwhile, you should check if the location of the library is correct, try to use `nvopencl32.dll`, etc.
Hello again,  
This is where I found nvopencl32
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_21a764822be8dff8
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5db32447b43ce666
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_e7b3660b4830c245

Cheers Kev 
Ps am running Windows 10pro

**Comment by claudioandre-br** [comment]
Windows is a crazy environment. It seems the driver is staged (but not installed?)!

> The process of copying a driver package to the driver store is called staging. A driver package must be staged to the driver store before the package can be used to install any devices. 

It there any OpenCL file inside `C:\Windows\System32`?

**Comment by solardiz** [comment]
@kevtheskin As you can see, we're wondering and trying to guess, but I thought I'd rather ask you directly: why didn't you use the john-users mailing list? What edit to the JtR homepage or whatever, if any, would have resulted in you using the mailing list for your user support request? Thanks!

**Comment by kevtheskin** [comment]
> 
> 
> I have to try to reproduce your environment.
> 
>     * Meanwhile, you should check if the location of the library is correct, try to use `nvopencl32.dll`, etc.
Hello again,  
This is where I found nvopencl32
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_21a764822be8dff8
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5db32447b43ce666
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_e7b3660b4830c245

Cheers Kev 
Ps am running Windows 10pro 





> 
> 
> Windows is a crazy environment. It seems the driver is staged (but not installed?)!
> 
> > The process of copying a driver package to the driver store is called staging. A driver package must be staged to the driver store before the package can be used to install any devices.
> 
> It there any OpenCL file inside `C:\Windows\System32`?

Hello Claudio, Nothing in the systems32 folder. Hashcat works with Gpu if that helps?

**Comment by solardiz** [comment]
FWIW, I just went through all of @kevtheskin's "11 contributions in the last year" on GitHub, and literally all of them are user support requests to various projects. Some of them contain information that might be helpful to projects, but only to the extent that we'd normally see on a user support forum like john-users. For some projects, this could be normal - some actually mix bug reports and development and user support like this, for not having a separate user support forum or/and being small projects. But for most larger projects I think it'd be misuse of GitHub.

Maybe it's just the modern trend. Maybe we could embrace it rather than fight it. I am unhappy about discussions staying on GitHub, and eventually dying with GitHub (yes, I do think JtR might have a longer life than GitHub as we know it now; JtR is much older than GitHub), but this applies to our development discussions to at least the same extent. ;-( So maybe we need to prioritize moving source code discussions back to john-dev over moving occasional misdirected support requests from GitHub to john-users. Unfortunately, as I understand magnum and Claudio actually prefer discussions on GitHub, so I'll have to accept that...

**Comment by kevtheskin** [comment]
> 
> 
> FWIW, I just went through all of @kevtheskin's "11 contributions in the last year" on GitHub, and literally all of them are user support requests to various projects. Some of them contain information that might be helpful to projects, but only to the extent that we'd normally see on a user support forum like john-users. For some projects, this could be normal - some actually mix bug reports and development and user support like this, for not having a separate user support forum or/and being small projects. But for most larger projects I think it'd be misuse of GitHub.
> 
> Maybe it's just the modern trend. Maybe we could embrace it rather than fight it. I am unhappy about discussions staying on GitHub, and eventually dying with GitHub (yes, I do think JtR might have a longer life than GitHub as we know it now; JtR is much older than GitHub), but this applies to our development discussions to at least the same extent. ;-( So maybe we need to prioritize moving source code discussions back to john-dev over moving occasional misdirected support requests from GitHub to john-users. Unfortunately, as I understand magnum and Claudio actually prefer discussions on GitHub, so I'll have to accept that...

Have just subscribed to the users-list

**Comment by claudioandre-br** [comment]
This is from a notebook bought a week ago. I did nothing:

``` 
C:\Users\Jucélia Zardini\Downloads\win_x64\run>john --list=build-info
Version: 1.8.0.13-jumbo-1-bleeding-1f1a862 2019-01-31 23:28:54 +0100
Build: cygwin 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
CPU fallback binary: john-xop
OMP fallback binary: john-avx2-non-omp
$JOHN is
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 6.4.0
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01000210f      (loaded: 0100020ef)
OpenSSL 1.0.2p  14 Aug 2018     (loaded: OpenSSL 1.0.2n  7 Dec 2017)
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

C:\Users\Jucélia Zardini\Downloads\win_x64\run>john --list=opencl-devices
Platform #0 name: NVIDIA CUDA, version: OpenCL 1.2 CUDA 9.1.84
    Device #0 (0) name:     GeForce MX150
    Device vendor:          NVIDIA Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2 CUDA
    Driver version:         391.25 [recommended]
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          2 GB
    Global Memory Cache:    48 KB
    Local Memory:           48 KB (Local)
    Constant Buffer size:   64 KB
    Max memory alloc. size: 512 MB
    Max clock (MHz):        1531
    Profiling timer res.:   1000 ns
    Max Work Group Size:    1024
    Parallel compute cores: 3
    CUDA cores:             384  (3 x 128)
    Speed index:            587904
    Warp size:              32
    Max. GPRs/work-group:   65536
    Compute capability:     6.1 (sm_61)
    Kernel exec. timeout:   yes
    PCI device topology:    01:00.0
```

**Comment by claudioandre-br** [comment]
You must complete the driver installation. The last version (I can see only one version here).

![image](https://user-images.githubusercontent.com/1702923/52977024-862c0700-33aa-11e9-80c3-c6f86223dc7b.png)

**Comment by claudioandre-br** [comment]
That said, this is not an error in JtR itself.
* The maintainer might block further discussions.

**Comment by kevtheskin** [comment]
> 
> 
> You must complete the driver installation. The last version (I can see only one version here).
> 
> ![image](https://user-images.githubusercontent.com/1702923/52977024-862c0700-33aa-11e9-80c3-c6f86223dc7b.png)

Hi there, When you say driver installation my Gpu appears to be installed correctly. Nvidia 418.91 ?

**Comment by kevtheskin** [comment]
Ps big thanks Claudio for your help

**Comment by claudioandre-br** [comment]
As a side note:
* Replace the cygwin's OpenCL library using the installed OpenCL DLL (in my case Intel's `OpenCL.dll` seen below) works and should be the first advice for anyone in Windows. It is now detecting all OpenCL hardware [1].

![image](https://user-images.githubusercontent.com/1702923/52978069-76aebd00-33ae-11e9-9555-37d487e31be1.png)

* Copy it to JtR run folder (the **old** dll and the copied and renamed file):

![image](https://user-images.githubusercontent.com/1702923/52978181-f0df4180-33ae-11e9-9f38-27041b26d983.png)

[1] The usage of the Windows native library is better.
```
C:\Users\Jucélia Zardini\Downloads\win_x64\run>john --list=opencl-devices
Platform #0 name: Intel(R) OpenCL, version: OpenCL 2.1
    Device #0 (0) name:     Intel(R) UHD Graphics 620
    Device vendor:          Intel(R) Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 2.1 NEO
    Driver version:         23.20.16.4973
    Native vector widths:   char 16, short 8, int 4, long 1
    Preferred vector width: char 16, short 8, int 4, long 1
    Global Memory:          3240 MB
    Global Memory Cache:    512 KB
    Local Memory:           64 KB (Local)
    Constant Buffer size:   1620 MB
    Max memory alloc. size: 1620 MB
    Max clock (MHz):        1150
    Profiling timer res.:   83 ns
    Max Work Group Size:    256
    Parallel compute cores: 24
    Stream processors:      192  (24 x 8)
    Speed index:            220800

    Device #1 (1) name:     Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Device vendor:          Intel(R) Corporation
    Device type:            CPU (LE)
    Device version:         OpenCL 2.1 (Build 611)
    Driver version:         7.6.0.611
    Native vector widths:   char 32, short 16, int 8, long 4
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          8101 MB
    Global Memory Cache:    256 KB
    Local Memory:           32 KB (Global)
    Constant Buffer size:   128 KB
    Max memory alloc. size: 2025 MB
    Max clock (MHz):        1800
    Profiling timer res.:   514 ns
    Max Work Group Size:    8192
    Parallel compute cores: 8
    Speed index:            57600

Platform #1 name: NVIDIA CUDA, version: OpenCL 1.2 CUDA 9.1.84
    Device #0 (2) name:     GeForce MX150
    Device vendor:          NVIDIA Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2 CUDA
    Driver version:         391.25 [recommended]
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          2 GB
    Global Memory Cache:    48 KB
    Local Memory:           48 KB (Local)
    Constant Buffer size:   64 KB
    Max memory alloc. size: 512 MB
    Max clock (MHz):        1531
    Profiling timer res.:   1000 ns
    Max Work Group Size:    1024
    Parallel compute cores: 3
    CUDA cores:             384  (3 x 128)
    Speed index:            587904
    Warp size:              32
    Max. GPRs/work-group:   65536
    Compute capability:     6.1 (sm_61)
    Kernel exec. timeout:   yes
    PCI device topology:    01:00.0
```

**Comment by magnumripper** [comment]
> Maybe it's just the modern trend. Maybe we could embrace it rather than fight it. I am unhappy about discussions staying on GitHub, and eventually dying with GitHub (yes, I do think JtR might have a longer life than GitHub as we know it now; JtR is much older than GitHub), but this applies to our development discussions to at least the same extent. ;-( So maybe we need to prioritize moving source code discussions back to john-dev over moving occasional misdirected support requests from GitHub to john-users. Unfortunately, as I understand magnum and Claudio actually prefer discussions on GitHub, so I'll have to accept that...

I do recognize the problem with all content here eventually going away. Apart from being brower based instead of mail based, I love the fact I can just write part of a commit like b7aca6b or refer to other topics, comments or even persons - and it all ends up as links and pings (to mentioned persons). Oh, and of course the issue/bug tracking and PR stuff are here (I could easily live with them, as well as the repo itself, being on Openwall). Using john-dev for all discussions while keeping issues and PR's here would be extremely messy, I can't even picture how that would work or look.

**Comment by kevtheskin** [comment]
> 
> 
> As a side note:
> 
>     * Replace the cygwin's OpenCL library using the installed OpenCL DLL (in my case Intel's `OpenCL.dll` seen below) works and should be the first advice for anyone in Windows. It is now detecting all OpenCL hardware [1].
> 
> 
> ![image](https://user-images.githubusercontent.com/1702923/52978069-76aebd00-33ae-11e9-9555-37d487e31be1.png)
> 
>     * Copy it to JtR run folder (the **old** dll and the copied and renamed file):
> 
> 
> ![image](https://user-images.githubusercontent.com/1702923/52978181-f0df4180-33ae-11e9-9f38-27041b26d983.png)
> 
> [1] The usage of the Windows native library is better.
> 
> ```
> C:\Users\Jucélia Zardini\Downloads\win_x64\run>john --list=opencl-devices
> Platform #0 name: Intel(R) OpenCL, version: OpenCL 2.1
>     Device #0 (0) name:     Intel(R) UHD Graphics 620
>     Device vendor:          Intel(R) Corporation
>     Device type:            GPU (LE)
>     Device version:         OpenCL 2.1 NEO
>     Driver version:         23.20.16.4973
>     Native vector widths:   char 16, short 8, int 4, long 1
>     Preferred vector width: char 16, short 8, int 4, long 1
>     Global Memory:          3240 MB
>     Global Memory Cache:    512 KB
>     Local Memory:           64 KB (Local)
>     Constant Buffer size:   1620 MB
>     Max memory alloc. size: 1620 MB
>     Max clock (MHz):        1150
>     Profiling timer res.:   83 ns
>     Max Work Group Size:    256
>     Parallel compute cores: 24
>     Stream processors:      192  (24 x 8)
>     Speed index:            220800
> 
>     Device #1 (1) name:     Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
>     Device vendor:          Intel(R) Corporation
>     Device type:            CPU (LE)
>     Device version:         OpenCL 2.1 (Build 611)
>     Driver version:         7.6.0.611
>     Native vector widths:   char 32, short 16, int 8, long 4
>     Preferred vector width: char 1, short 1, int 1, long 1
>     Global Memory:          8101 MB
>     Global Memory Cache:    256 KB
>     Local Memory:           32 KB (Global)
>     Constant Buffer size:   128 KB
>     Max memory alloc. size: 2025 MB
>     Max clock (MHz):        1800
>     Profiling timer res.:   514 ns
>     Max Work Group Size:    8192
>     Parallel compute cores: 8
>     Speed index:            57600
> 
> Platform #1 name: NVIDIA CUDA, version: OpenCL 1.2 CUDA 9.1.84
>     Device #0 (2) name:     GeForce MX150
>     Device vendor:          NVIDIA Corporation
>     Device type:            GPU (LE)
>     Device version:         OpenCL 1.2 CUDA
>     Driver version:         391.25 [recommended]
>     Native vector widths:   char 1, short 1, int 1, long 1
>     Preferred vector width: char 1, short 1, int 1, long 1
>     Global Memory:          2 GB
>     Global Memory Cache:    48 KB
>     Local Memory:           48 KB (Local)
>     Constant Buffer size:   64 KB
>     Max memory alloc. size: 512 MB
>     Max clock (MHz):        1531
>     Profiling timer res.:   1000 ns
>     Max Work Group Size:    1024
>     Parallel compute cores: 3
>     CUDA cores:             384  (3 x 128)
>     Speed index:            587904
>     Warp size:              32
>     Max. GPRs/work-group:   65536
>     Compute capability:     6.1 (sm_61)
>     Kernel exec. timeout:   yes
>     PCI device topology:    01:00.0
> ```

Claudio you cracked it for me . This worked a treat . Thank you Kev

**Comment by boohboot** [comment]
> 
> 
> 3x nvopencl32.dll and 3x nvopencl64.dll all located in the FileRepository
> 
> Cheers Kev

Copy file "nvopencl64.dll" to system32 and alter c:\Windows\System32\nvopencl.dll to c:\Windows\System32\nvopencl64.dll in nvidia.icd save and retry, worked for me with gtx660

**Comment by orfeous1** [comment]
Thank you, had the same problem. Works great now GTX760

**Comment by orfeous1** [comment]
Edit by @solardiz: over-quoting of the comment from Claudio deleted, leaving only 3 most-relevant lines.

> C:\Users\Jucélia Zardini\Downloads\win_x64\run>john --list=opencl-devices
> Platform #0 name: Intel(R) OpenCL, version: OpenCL 2.1
>     Device #0 (0) name:     Intel(R) UHD Graphics 620

Ah, you gave me an idea, i want to utilize my intel GPU also. Intel GPU, Nvidia GPU and my CPU.
Any special options/commands for that? Will it improve my performance?
For now it seems that my Nvidia GPU are burst loaded on and off on and off.. while cpu are loaded with about 30-50%

**Comment by ghost** [comment]
> i want to utilize my intel GPU also.

If you have all drivers installed, all devices should be listed by `--list=opencl-devices` and to use them you only need to specify  `--device=n` in the command line.

**Comment by solardiz** [comment]
> Will it improve my performance?
> For now it seems that my Nvidia GPU are burst loaded on and off on and off.. while cpu are loaded with about 30-50%

I'll refrain from addressing semi-off-topic questions on this GitHub issue. @orfeous1 Please feel free to ask those questions on the john-users mailing list, where they belong. If/when you do, please also describe your use case, the JtR format you use, etc., so that people can possibly help you with your actual goal, not merely with troubleshooting individual issues. However, once again, this is really not GitHub issue tracker material.

**Comment by orfeous1** [comment]
Intel drivers are installed, but does not show up in the "john --list=opencl-devices" only ny nvidia.
Im refering to @claudioandre-br 's post showing three devices. I also have those devices in my computer.
Something must be missing or else im doing something wrong.

Using --format=rar-opencl and trying to check for rar-password. But its really slow and time consuming.
So i want to use all available resources i can feed john with to optimize the time/performance.

EDIT: Got it working with intel. Copied nvidia.icd in vendors folder and renamed it to intel, then specified IntelOpencl64.dll.
Now i can see two platforms and three devices. Dont know if i specified the correct opencl-driver though. There was a lot of different ones.

```
C:\Users\Anton\Downloads\john-1.9.0-jumbo-1-win64\run>john --list=opencl-devices
Platform #0 name: Intel(R) OpenCL, version: OpenCL 1.2
    Device #0 (1) name:     Intel(R) HD Graphics 4600
    Device vendor:          Intel(R) Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2
    Driver version:         20.19.15.5166
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          1629 MB
    Global Memory Cache:    256 KB
    Local Memory:           64 KB (Local)
    Constant Buffer size:   64 KB
    Max memory alloc. size: 407 MB
    Max clock (MHz):        1200
    Profiling timer res.:   80 ns
    Max Work Group Size:    512
    Parallel compute cores: 20
    Stream processors:      160  (20 x 8)
    Speed index:            192000

    Device #1 (2) name:     Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
    Device vendor:          Intel(R) Corporation
    Device type:            CPU (LE)
    Device version:         OpenCL 1.2 (Build 10094)
    Driver version:         5.2.0.10094
    Native vector widths:   char 32, short 16, int 8, long 4
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          16252 MB
    Global Memory Cache:    256 KB
    Local Memory:           32 KB (Global)
    Constant Buffer size:   128 KB
    Max memory alloc. size: 4063 MB
    Max clock (MHz):        3400
    Profiling timer res.:   100 ns
    Max Work Group Size:    8192
    Parallel compute cores: 4
    Speed index:            54400

Platform #1 name: NVIDIA CUDA, version: OpenCL 1.2 CUDA 11.2.66
    Device #0 (3) name:     GeForce GTX 760
    Device vendor:          NVIDIA Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2 CUDA
    Driver version:         460.89 [recommended]
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          2 GB
    Global Memory Cache:    96 KB
    Local Memory:           48 KB (Local)
    Constant Buffer size:   64 KB
    Max memory alloc. size: 512 MB
    Max clock (MHz):        1150
    Profiling timer res.:   1000 ns
    Max Work Group Size:    1024
    Parallel compute cores: 6
    CUDA cores:             1152  (6 x 192)
    Speed index:            1324800
    Warp size:              32
    Max. GPRs/work-group:   65536
    Kernel exec. timeout:   yes
    PCI device topology:    01:00.0
```

```
C:\Users\Anton\Downloads\john-1.9.0-jumbo-1-win64\run>john --devices=1,2,3 --restore
Device 3: GeForce GTX 760
Loaded 1 password hash (rar-opencl, RAR3 [SHA1 OpenCL AES])
Will run 4 OpenMP threads
Proceeding with incremental:ASCII
Press 'q' or Ctrl-C to abort, almost any other key for status
```

While doing some test using all three devices seems to have slower virtual performance.

```
C:\Users\Anton\Downloads\john-1.9.0-jumbo-1-win64\run>john --test=10 --format=mscash2-opencl  -dev=1,2,3
Benchmarking: mscash2-opencl, MS Cache Hash 2 (DCC2) [PBKDF2-SHA1 OpenCL]... Device 1: Intel(R) HD Graphics 4600
Device 2: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
Device 3: GeForce GTX 760
DONE
Raw:    20091 c/s real, 7798 c/s virtual

C:\Users\Anton\Downloads\john-1.9.0-jumbo-1-win64\run>john --test=10 --format=mscash2-opencl  -dev=1,3
Benchmarking: mscash2-opencl, MS Cache Hash 2 (DCC2) [PBKDF2-SHA1 OpenCL]... Device 1: Intel(R) HD Graphics 4600
Device 3: GeForce GTX 760
DONE
Raw:    19487 c/s real, 19504 c/s virtual
```

Edit by @solardiz: added backticks around the commands and their output.

**Comment by ghost** [comment]
For future reference:

* to help checking if you have OpenCL working:
https://ci.appveyor.com/api/projects/oblomov/clinfo/artifacts/clinfo.exe?job=platform%3a+x64
* to fully use the 3 device, you need `fork` (in all formats but mscash2, I think)
```
../run/john --devices=1,2,3 --fork=3 --format=rar-opencl FILENAME
```

**Comment by solardiz** [comment]
> Using --format=rar-opencl and trying to check for rar-password.

This is now on john-users (thanks!), so I am going to comment further in there: https://www.openwall.com/lists/john-users/2021/01/04/1

> EDIT: Got it working with intel. Copied nvidia.icd in vendors folder and renamed it to intel, then specified IntelOpencl64.dll.

Great to know, and can be useful to others reading this. Thanks! (I think most people readily have this kind of configuration out of the box, though. I don't know why you did not.)

> john --devices=1,2,3 --restore

You cannot do that. It was a bug (which we've since fixed in our current code in this repository) that `--restore` didn't reject some other options used along with it. You can only specify `--devices=1,2,3 --fork=3` when starting a new session, not when restoring. But in your specific case, you shouldn't even do that.

> slower virtual performance.

Please don't look at the virtual numbers at all unless you're really familiar with what they are and have a use for them. Also, the `mscash2-opencl` format is unlike all others in its ability to use multiple devices without `--fork`.

> ../run/john --devices=1,2,3 --fork=3 --format=rar-opencl FILENAME

While that's how you'd have `john` use multiple devices, I think it's a bad idea to do so for the specific combination of devices we see here, as well as for `rar-opencl`. An approach like this works well for devices that are similar to each other, not for very different devices. When using JtR, it's also generally a bad idea to use the CPU via OpenCL - on CPU, our separate CPU formats (those without `-opencl` in their names) generally perform better.

**Comment by duckstroms** [comment]
**E:\john\run>john --list=opencl-devices**
```
Error: No OpenCL-capable platforms were detected by the installed OpenCL driver.
Error: No OpenCL-capable devices were detected by the installed OpenCL driver.
```

what hapeend ? can help me now.

**Comment by EagerSun09** [comment]
I used the tool clinfo.exe and also moved my nvopencl32.dll, nvopencl64.dll and nvopencl.dll to System32 and even the run folder in JtR. However, I still get the error 'No OpenCL-capable platforms were detected by the installed OpenCL driver.
Error: No OpenCL-capable devices were detected by the installed OpenCL driver.'
Any help would be appreciated! Thanks!

**Comment by ghost** [comment]
Replying to a recent post (the author deleted the message, it seems)

To make a Windows build work with OpenCL you need:
  - Copy the proper opencl DLL file to the run folder;
  - Then, rename the copied file to cygOpenCL-1.dll;
    - Notice that sometimes there are some mysterious extra OpenCL DLL files in Windows. This is Windows magic, I have no idea where they came from. If you find too many DLL files, try them all one at a time: copy, rename, test; copy another file, rename and ...

Regedit can be a source of information (which is the proper DLL file), but I'm sure I've run into some situation where nothing exists inside the Windows registry.

**Comment by EagerSun09** [comment]
> Replying to a recent post (the author deleted the message, it seems)
> 
> To make a Windows build work with OpenCL you need:
> 
> * Copy the proper opencl DLL file to the run folder;
> * Then, rename the copied file to cygOpenCL-1.dll;
>   
>   * Notice that sometimes there are some mysterious extra OpenCL DLL files in Windows. This is Windows magic, I have no idea where they came from. If you find too many DLL files, try them all one at a time: copy, rename, test; copy another file, rename and ...
> 
> Regedit can be a source of information (which is the proper DLL file), but I'm sure I've run into some situation where nothing exists inside the Windows registry.

Hi Claudio. I deleted my comment. I successfully run JtR with my video card by restarting the PC. I just don't want you to repeat same words again again and again which is annoying. Thanks for your help, I learned a lot from this thread.

**Comment by ghost** [comment]
> I successfully run JtR with my video card by restarting the PC

The restart is new to me. Good to have it documented here.

**Comment by ghost** [comment]
Primary Solution: Modify the NVIDIA ICD File
This was the fix that worked for the original poster and others in the thread.

Navigate to the OpenCL vendors folder inside your John the Ripper directory. The path is typically:

text
C:\Users\YourUsername\Desktop\win_x64\etc\OpenCL\vendors\
(The exact path will depend on where you extracted John the Ripper).

Locate the nvidia.icd file in that folder. This file tells the system which OpenCL driver to load for NVIDIA devices.

Edit the nvidia.icd file using a text editor like Notepad. You will likely see a single line inside, which is the name of a DLL file.

Change the DLL name from nvopencl.dll to nvopencl64.dll.

Save the file and try running the command again: john --list=opencl-devices.

**Comment by solardiz** [comment]
@lebcosty Thanks, but I guess you were using our older 1.9.0-jumbo-1 release, which is why you ran into this issue in the first place? We ought to make a new release, but meanwhile:

We've since made changes to John the Ripper jumbo source code to have it find and load the OpenCL DLL itself, this was PR #5386 and it was merged before the latest set of Windows builds were made available at https://github.com/openwall/john-packages/releases as described in https://github.com/openwall/john-packages#-windows - so _that_ should be the current primary solution, instead of having to make changes on the system like comments above and in #3191 used to describe.
